const char *ssid = "Linksys";
const char *password = "Europe3224.";
int y=103;                           // ------------------------- dernier chiffres de IP -----------------------------
//const char API_KEY[] = "JTHVS3SYEhBZbgh3JIkU00vefcNjddiPd0xpkE0Z2pRfG8xy6C92rqjFgsnqu8dJ";
//const char HOST_JEEDOM[] = "192.168.1.85";
//const char ID[] = "1357";               // ******************** ID virtuel Jeedom ************************  
//const char ID_JETON[] = "1358";               // ******************** ID jeton virtuel Jeedom ************************    
byte NbJETON = 4;                   // Nombre de jetons (- 1 )          **** 17 KG  (4)  ******* 14 Kg (2) ********** 10 Kg (1)************
byte IMPULSE = 50;                  // ***************   Temps d'impulsion en millisecondes pour la sélection de l'essorage ****************  